#!/usr/bin/env python

Import('env')
Import('env_modules')


if (env["platform"] == "iphone"):
    env.add_source_files(env.modules_sources, "ios/*.mm")
    env.add_source_files(env.modules_sources, "*.cpp")
